version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: service_ngnix
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
