version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: service_ngnix
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./secrets:/ssl/
    ports:
      - 80:80
      - 443:443
